# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestauranteImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='', verbose_name='Subir Imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=500)),
                ('precio', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Restaurantes',
                'verbose_name': 'Restaurante',
            },
        ),
    ]
